name: 评测

on:
  push:
    branches:
      - main
    paths:
      - main.c
      - main.py

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    env:
      MY_URL: ${{ secrets.MY_URL }}
    steps:
      - name: 检出仓库
        uses: actions/checkout@v3
        
      - name: 安装依赖
        run: |
          if [ -z "${MY_URL}" ]; then
            echo "未设置 MY_URL"
            exit 0  # 退出
          fi
          sudo apt-get update
          sudo apt-get install -y gcc-11 python3
          pip3 install pandas==2.2.3 numpy==2.1.2

      - name: 测试
        run: |
          if [ -z "${MY_URL}" ]; then
            echo "未设置 MY_URL"
            exit 0  # 退出
          fi
          git clone https://${MY_URL}:x-oauth-basic@github.com/NGC2237plus/c-cpp_test.git
          cd c-cpp_test
          python3 test.py
